version: '3.7'
services:
    minecraft:
        build: .
        volumes:
            - minecraft_server:/home/minecraft/minecraft_server
        ports:
            - 25565:25565

volumes:
    minecraft_server:
